name: recipe_app
description: A Flutter recipe application using TheMealDB API.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  path: ^1.9.0
  cached_network_image: ^3.4.0
  provider: ^6.1.2
  flutter_local_notifications: ^17.2.3
  android_intent_plus: ^5.1.0
  url_launcher: ^6.3.0
  speech_to_text: ^7.0.0
  googleapis: ^11.0.0
  googleapis_auth: ^1.6.0

flutter:
  assets:
    